inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - lib/generators/**/*
    - vendor/bundle/**/*

LineLength:
  Enabled: false

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Max: 30
