inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  Exclude:
    - gemfiles/vendor/bundle/**/* # This dir only shows up on Travis
    - lib/generators/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/StderrPuts:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
