before_script: psql -c 'create database rpush_test;' -U postgres >/dev/null
language: ruby
install: bundle install --jobs=4
services:
- redis-server
matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.1.2
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.0.0
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  - rvm: 2.1.2
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.1.2
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.0.0
    gemfile: Gemfile.rails-4
    env: CLIENT=redis
  - rvm: 2.1.2
    gemfile: Gemfile.rails-4
    env: CLIENT=redis
  - rvm: 2.1.2
    gemfile: Gemfile
    env: CLIENT=active_record ADAPTER=sqlite3
  - rvm: rbx-2
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  - rvm: jruby
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  allow_failures:
  - rvm: rbx-2
  - rvm: jruby
env:
  global:
    secure: NmFJ2Wk0W4mCce7pLXNcuQEd7Omr+XQxXyVlOQMtve6wwLv+R6r49Rgx7EkkbHd6OhspYoprtGsOPYE1c1fGOXn9Cd9Lf+SXNMmLnhXlvXWY1GDv2ULzL1cbu9dtc7KoHXkFmWYGqjuHzB5IkBFNqSKWaF4L4iM4Oh6MFE4kZ2M=
