before_script: "psql -c 'create database rpush_test;' -U postgres >/dev/null"
language: ruby
install: bundle install --local --deployment --no-prune --no-cache --jobs=4
services:
  - redis-server

matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.1.2
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.0.0
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  - rvm: 2.1.2
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.1.2
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.0.0
    gemfile: Gemfile.rails-4
    env: CLIENT=redis
  - rvm: 2.1.2
    gemfile: Gemfile.rails-4
    env: CLIENT=redis
  - rvm: 2.1.2
    gemfile: Gemfile
    env: CLIENT=active_record ADAPTER=sqlite3
  - rvm: rbx
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  - rvm: jruby
    gemfile: Gemfile.rails-4
    env: CLIENT=active_record
  allow_failures:
    - rvm: rbx
    - rvm: jruby
    - env: CLIENT=active_record ADAPTER=sqlite3
