language: ruby

sudo: false

services:
  - redis-server

before_script: psql -c 'create database rpush_test;' -U postgres >/dev/null

install: tools/cached-bundle install --deployment

matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.1.5
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.1.5
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.0.0
    gemfile: Gemfile.rails-3
    env: CLIENT=redis
  - rvm: 2.1.5
    gemfile: Gemfile.rails-3
    env: CLIENT=redis
  - rvm: 2.0.0
    gemfile: Gemfile.rails-3
    env: CLIENT=active_record
  - rvm: 2.1.5
    gemfile: Gemfile.rails-3
    env: CLIENT=active_record
  - rvm: 1.9.3
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 1.9.3
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: rbx-2.4.1
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: rbx-2.4.1
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: jruby-1.7.16
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: jruby-1.7.16
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.2.0-preview2
    gemfile: Gemfile
    env: CLIENT=active_record
  allow_failures:
    - rvm: 2.2.0-preview2
    - rvm: 1.9.3
